version: '3.4'

services:
  redis:
    image: redis:alpine
    ports:
      - "5776:6379"
  restaurantservice:
    image: ${DOCKER_REGISTRY-}restaurantservice
    build:
      context: .
      dockerfile: RestaurantService/Dockerfile

  restaurantservice-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "restaurantservice", "-app-port", "80", "-components-path", "/components","-placement-host-address", "dapr-placement:50000" ]
    volumes:
      - "./dapr/components:/components"
    depends_on:
      - restaurantservice
    network_mode: "service:restaurantservice" 

  platform:
    image: ${DOCKER_REGISTRY-}platform
    build:
      context: .
      dockerfile: Platform/Dockerfile

  platform-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "platform", "-app-port", "80", "-components-path", "/components", "-placement-host-address", "dapr-placement:50000" ]
    volumes:
      - "./dapr/components:/components"
    depends_on:
      - platform
      - redis
    network_mode: "service:platform"


  dapr-placement:
    image: "daprio/dapr:latest"