kind: Service
apiVersion: v1
metadata:
  name: platform
  labels:
    app: platform
spec:
  selector:
    app: platform
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
  labels:
    app: platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "platform"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: platform
        image: mddevdays.azurecr.io/platform:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
